version: "3.2"
services:
 node_project:
  build: 
   context: .
   args:
    NODE_ENV: development
  volumes: 
   - ./:/app
   - /app/node-modules
  environment:
   - NODE-ENV=development
  command: npm run dev
